experiment_name: 'baseline'

dataset: 'chembl'
num_epochs: 1000
batch_size: 1000
log_iterations: 30
patience: 30
loss_func: BCEWithLogitsLoss
num_train: 380000
required_data:
  - dgl_graph
metrics:
  - accuracy
optimizer: Adam
optimizer_params:
  lr: 1.0e-4
collate_function: MaskedCollate
collate_params:
  mask_probability: 0.2

scheduler_step_per_batch: False
lr_scheduler: WarmUpWrapper
lr_scheduler_params:
  warmup_steps: [1500]
  interpolation: 'linear'
  # parameters of scheduler to run after warmup
  wrapped_scheduler: ReduceLROnPlateau
  factor: 0.5
  patience: 25
  min_lr: 5.0e-6
  mode: 'max'
  verbose: True

# Model parameters
model_type: 'ELECTRA'
model_parameters:
  pna_generator_args:
    hidden_dim: 50
    mid_batch_norm: True
    last_batch_norm: True
    # e^(log(forgetfulness ~0.001)/number of steps per epoch) = batch_norm_momentum   =>  e^(log(0.001)/100) = 0.970
    batch_norm_momentum: 0.1
    dropout: 0.0
    propagation_depth: 3
    aggregators:
      - mean
      - max
      - min
      - std
    scalers:
      - identity
      - amplification
      - attenuation
    pretrans_layers: 2
    posttrans_layers: 2
    residual: True
  pna_discriminator_args:
      hidden_dim: 50
      mid_batch_norm: True
      last_batch_norm: True
      # e^(log(forgetfulness ~0.001)/number of steps per epoch) = batch_norm_momentum   =>  e^(log(0.001)/100) = 0.970
      batch_norm_momentum: 0.1
      dropout: 0.0
      propagation_depth: 3
      aggregators:
        - mean
        - max
        - min
        - std
      scalers:
        - identity
        - amplification
        - attenuation
      pretrans_layers: 2
      posttrans_layers: 2
      residual: True